version: "3.8"

services:
  mysqldb:
    platform: linux/arm64
    image: mysql:8
    restart: unless-stopped
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQLDB_PASSWORD}
      MYSQL_DATABASE: ${MYSQLDB_DATABASE}
    ports:
      - "${MYSQLDB_LOCAL_PORT}:${MYSQLDB_DOCKER_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQLDB_PASSWORD"]
      interval: 20s
      timeout: 5s
      retries: 10
  app:
    depends_on:
      mysqldb:
        condition: service_healthy
    restart: on-failure
    image: cdu-backend-service
    build: .
    env_file: ./.env
    ports:
      - "${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}"
      - "${DEBUG_PORT}:${DEBUG_PORT}"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url" : "jdbc:mysql://mysqldb:${MYSQLDB_DOCKER_PORT}/${MYSQLDB_DATABASE}?autoReconnect=true&useSSL=false",
        "spring.datasource.username" : "${MYSQLDB_USERNAME}",
        "spring.datasource.password" : "${MYSQLDB_PASSWORD}",
        "spring.datasource.initialization-mode": "always",
        "spring.mail.username" : "${EMAIL_SENDER_USERNAME}",
        "spring.mail.password" : "${EMAIL_SENDER_PASSWORD}",
        "form.mail.recipient" : "${EMAIL_RECIPIENT_USERNAME}",
        "dropbox.refresh.token" : "${DROPBOX_REFRESH_TOKEN}",
        "dropbox.app.key" : "${DROPBOX_APP_KEY}", 
        "dropbox.app.secret" : "${DROPBOX_APP_SECRET}",
        "dropbox.app.name" : "${DROPBOX_APP_NAME}",
        "dropbox.news.folder" : "${DROPBOX_NEWS_FOLDER}",
        "dropbox.team.member.folder" : "${DROPBOX_TEAM_MEMBERS_FOLDER}",
        "dropbox.fundraising.folder" : "${DROPBOX_FUNDRAISING_FOLDER}",
        "jwt.expiration" : "${JWT_EXPIRATION}"
      }'
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
